export const zimbabweLocations = [
  // Harare Suburbs
  "Avondale, Harare",
  "Borrowdale, Harare",
  "Mount Pleasant, Harare",
  "Glen Lorne, Harare",
  "Greendale, Harare",
  "Belgravia, Harare",
  "Highlands, Harare",
  "Marlborough, Harare",
  "Newlands, Harare",
  "Alexandra Park, Harare",
  "Gunhill, Harare",
  "Chisipite, Harare",
  "Greystone Park, Harare",
  "Hatfield, Harare",
  "Eastlea, Harare",
  "Arcadia, Harare",
  "Milton Park, Harare",
  "Waterfalls, Harare",
  "Warren Park, Harare",
  "Mbare, Harare",
  "Highfield, Harare",
  "Glen View, Harare",
  "Budiriro, Harare",
  "Mabvuku, Harare",
  "Tafara, Harare",
  
  // Bulawayo Suburbs
  "Hillside, Bulawayo",
  "Burnside, Bulawayo",
  "Matsheumhlope, Bulawayo",
  "Suburbs, Bulawayo",
  "Kumalo, Bulawayo",
  "North End, Bulawayo",
  "Bradfield, Bulawayo",
  "Newton West, Bulawayo",
  "Nketa, Bulawayo",
  "Pumula, Bulawayo",
  
  // Other Major Cities
  "Mutare",
  "Gweru",
  "Kwekwe",
  "Kadoma",
  "Masvingo",
  "Chinhoyi",
  "Norton",
  "Marondera",
  "Ruwa",
  "Chitungwiza",
  "Bindura",
  "Victoria Falls",
];
